# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
      - main
      - us/*
  paths:
    exclude:
      - CICD
    include:
      - backend

stages:
- stage: BuildPlatformGateway
  displayName: Build stage
  jobs:
  - job: BuildJob
    pool:
      vmImage: 'ubuntu-latest'

    steps:
        
    - task: Maven@3
      displayName: 'Package jar'
      inputs:
        mavenPomFile: 'backend/manager/pom.xml'
        options: '-DskipITs -X -Pprod'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: true
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
        
    - task: CopyFiles@2
      displayName: 'Copy Service Files'
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)/application'
        Contents: '**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)/dist/application'
        OverWrite: false
        
    - task: CopyFiles@2
      displayName: 'Copy Documents'
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)/docs'
        Contents: '**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)/dist/docs'
        OverWrite: false

    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/dist'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.Repository.Name)-$(Build.BuildNumber).zip'
        replaceExistingArchive: true

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.Repository.Name)-$(Build.BuildNumber).zip'
        ArtifactName: 'drop'
        publishLocation: 'Container'
      enabled: true

